[package]
name = "dais-remote"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/dais-remote"
keywords.workspace = true
categories.workspace = true
description = "Local HTTP remote-control API for Dais"
readme = "README.md"

[dependencies]
dais-core = { workspace = true }
dais-document = { workspace = true }

anyhow = { workspace = true }
fastrand = { workspace = true }
image = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
