[package]
name = "dais-sidecar"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Sidecar format abstraction and .pdfpc implementation for Dais"

[dependencies]
dais-core = { workspace = true }

serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
